name: Publish package to NPM

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  publish-npm:
    runs-on: windows-latest
    steps:
      - name: Set Node.js version for JavaScript Actions
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
        run: echo "Node.js version is set to 20"

      - name: Install Dependencies
        run: npm install

      - name: Build the Plugin
        run: npm run build  # Replace with your build command if necessary

      - name: Publish the Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
