name: Create new release

env:
  plugin_name: auto-champion-select

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths:
      - index.js
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Create Directory
        run: mkdir ${{ env.plugin_name }}

      - name: Move Files to Directory
        run: mv index.js README.md ${{ env.plugin_name }}

      - name: Zip Directory
        run: zip -r ${{ env.plugin_name }}.zip ${{ env.plugin_name }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with your tag name
          release_name: Release v1.0.0  # Replace with your release name
          body: |
            Release v1.0.0
            - Added index.js and README.md
          draft: false
          prerelease: false
          files: ${{ env.plugin_name }}.zip
