name: Create new release

env:
  plugin_name: auto-champion-select

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths:
      - index.js
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Creating a folder
        run: mkdir ${{ env.plugin_name }}

      - name: Moving files to the folder
        run: mv index.js README.md README.br.md ${{ env.plugin_name }}

      - name: Zipping the folder
        run: zip -r ${{ env.plugin_name }}.zip ${{ env.plugin_name }}

      - name: Creating the release
